apiVersion: apps/v1
kind: Deployment
metadata:
  name: htmlweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: htmlweb
  template:
    metadata:
      labels:
        app: htmlweb
    spec:
      containers:
      - name: server
        image: htmlweb
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        # This environment variable enables debugging support for the container.
        # Remove this to disable the debug build.
        - name: JAVA_TOOL_OPTIONS
          value: -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
